tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "mdogan/zulu"
tap "robotsandpencils/made"
brew "aria2"
brew "asdf"
brew "dotnet"
brew "fish"
brew "gh"
brew "git"
brew "git-lfs"
brew "htop"
brew "kdoctor"
brew "mas"
brew "xz"
brew "pre-commit"
brew "yq"
brew "robotsandpencils/made/xcodes"
cask "1password"
cask "brave-browser"
cask "logitech-options"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "mono-mdk-for-visual-studio"
cask "synology-drive"
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
vscode "Angular.ng-template"
vscode "bradlc.vscode-tailwindcss"
vscode "chrisbibby.hide-node-modules"
vscode "csstools.postcss"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "mathiasfrohlich.Kotlin"
vscode "mattpocock.ts-error-translator"
vscode "mechatroner.rainbow-csv"
vscode "mikerhyssmith.ts-barrelr"
vscode "ms-dotnettools.csharp"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-vsliveshare.vsliveshare"
vscode "Orta.vscode-ios-common-files"
vscode "rbbit.typescript-hero"
vscode "sswg.swift-lang"
vscode "vadimcn.vscode-lldb"
vscode "vscjava.vscode-gradle"
vscode "yzhang.markdown-all-in-one"
